### ISSUE TITLE
Revised UI Workflow

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#27]
Based on discussions at weekly meetings and in the design approach ticket #2 - the HOT team put together a sketch for a user experience. Hopefully @szymonkaliski you can review and we can all discuss at tomorrow's meeting! cc @smit1678 @mataharimhairi 

https://docs.google.com/presentation/d/1GgnhW1ISCX5AyMnY8mT1oPFMUUnJfdgiiZIEfipIpVI/edit?usp=sharing

**Comment by szymonkaliski** [comment]
This is looking good, and I'm happy that it's not far from what we were discussing in the design issue.

I left some comments on the slides, and have one important question here: 

What style would you like to keep this in? We could follow the other tools you already have, or use one of the two design styles we proposed in the other issue (https://github.com/hotosm/visualize-change/issues/2#issuecomment-365861668 or https://github.com/hotosm/visualize-change/issues/2#issuecomment-366643464)

Also, the "wizard" UX is not a good decision here in my opinion — it makes sense for situations where users have to make _a lot_ of _complex_ decisions, in very _specific order_. 
Here the decisions are not complex, and the order doesn't matter (it doesn't matter if user first specifies dates and then styles, or the other way around), but if you want to take it in this direction anyways, let's do it. 

Please answer my question about style, and confirm that this is how you want the tool to work, and I'll prepare some steps/approach to building this.

**Comment by awright** [comment]
I made comments to your comments on the slide deck. Note that we were not thinking of a Wizard UX but the user actions for each tab. 

What do you mean by "style"?

**Comment by szymonkaliski** [comment]
> Note that we were not thinking of a Wizard UX but the user actions for each tab.

Sure, for me the progression "1/2/3" and "next" button makes it feel like a "wizard". Do you think we could remove them to have it feel less like a "wizard"?

> What do you mean by "style"?

A "theme" - colors, fonts, element styling etc... so not layout of elements or ux - where they are and what functions they have, but how they look.

**Comment by awright** [comment]
On Tue, Feb 27, 2018 at 12:42 PM, Szymon Kaliski <notifications@github.com>
wrote:

> Note that we were not thinking of a Wizard UX but the user actions for
> each tab.
>
> Sure, for me the progression "1/2/3" and "next" button makes it feel like
> a "wizard". Do you think we could remove them to have it feel less like a
> "wizard"?
>
I think we can have Next and Cancel without it being like a wizard but
really interested to hear what others thing and/or to see it "live" so we
can comment and experience it.

> What do you mean by "style"?
>
> A "theme" - colors, fonts, element styling etc... so not layout of
> elements or ux - where they are and what functions they have, but how they
> look.
>

The workflow is definitely not meant as any indication of style. They are
like napkin sketches with the materials we could find online. We would
appreciate your own recommendations on style and can respond in kind.

Hope that helps!

**Comment by szymonkaliski** [comment]
> > > Note that we were not thinking of a Wizard UX but the user actions for
 each tab.
> >
> > Sure, for me the progression "1/2/3" and "next" button makes it feel like
 a "wizard". Do you think we could remove them to have it feel less like a
 "wizard"?
>
> I think we can have Next and Cancel without it being like a wizard but
really interested to hear what others thing and/or to see it "live" so we
can comment and experience it.

@mataharimhairi @smit1678 could you pitch in on that?

> The workflow is definitely not meant as any indication of style. They are
like napkin sketches with the materials we could find online. We would
appreciate your own recommendations on style and can respond in kind.

Would you like to see this in one of the styles we prepared earlier in the design document (white/red, or black/blue), or some other design altogether? Is you want something made from scratch, could you send some design references that you are thinking about?
Thanks!

**Comment by awright** [comment]
On Wed, Feb 28, 2018 at 3:35 AM, Szymon Kaliski <notifications@github.com>
wrote:

> Note that we were not thinking of a Wizard UX but the user actions for
> each tab.
>
> Sure, for me the progression "1/2/3" and "next" button makes it feel like
> a "wizard". Do you think we could remove them to have it feel less like a
> "wizard"?
>
> I think we can have Next and Cancel without it being like a wizard but
> really interested to hear what others thing and/or to see it "live" so we
> can comment and experience it.
>
> @mataharimhairi <https://github.com/mataharimhairi> @smit1678
> <https://github.com/smit1678> could you pitch in on that?
>
would it be possible to see this in action and we can comment on it?

> The workflow is definitely not meant as any indication of style. They are
> like napkin sketches with the materials we could find online. We would
> appreciate your own recommendations on style and can respond in kind.
>
> Would you like to see this in one of the styles we prepared earlier in the
> design document (white/red, or black/blue), or some other design
> altogether? Is you want something made from scratch, could you send some
> design references that you are thinking about?
>
it would be great to see the white/red version. let's go from there.
thanks!

**Comment by szymonkaliski** [comment]
Ok so let's do this:

1. we'll make the design, and post here for approval
2. after we get the "green light" we'll start with the basic setup - the main view of the application, with just the _bare minium_ required for it to work (basically tabs with options and preview)
3. after testing/playing with 2. we will move forward to adding more features, start page, etc.

This should give us a prototype version fairly soon (although incomplete). How does that sound?

**Comment by awright** [comment]
Thanks Szymon. What do you mean by "we'll make the design"? I am not sure I
understand the distinction between Point 1 and 2 above. Thanks!

**Comment by szymonkaliski** [comment]
>Thanks Szymon. What do you mean by "we'll make the design"? I am not sure I
understand the distinction between Point 1 and 2 above. Thanks!

1. is an image, 2. is in code :)

**Comment by awright** [comment]
Sounds good. Let's move forward with 1, but I'd like to make sure we allow
time and iteration for our feedback on 2. I think we can move quickly on
1.

**Comment by szymonkaliski** [comment]
Yeah sure, we should send 1. tomorrow, and we can start on 2. once we get thumbs up on this.

**Comment by awright** [comment]
Perfect. Thanks!

**Comment by szymonkaliski** [comment]
So, we started with slides 2-4 as they seem most important, I'd prefer to implement just this part first, and then design and implement other slides.

Slide 2:

![1](https://user-images.githubusercontent.com/1040420/36850052-004657d6-1d66-11e8-9410-26b9873a25ab.png)

Slide 3:

![2](https://user-images.githubusercontent.com/1040420/36850064-08904c4e-1d66-11e8-98f3-3addeff7483a.png)

Slide 4:

![3](https://user-images.githubusercontent.com/1040420/36850068-0bce27d2-1d66-11e8-9024-a34ef8b5ebb9.png)

As you can see we made very small changes to the layout (for example moving the big bottom bar, to fit inside of the sidebar). 
Sadly, with this UI, we have some wasted whitespace in the sidebar (something that we tried to avoid by having the options as vertically collapsable panes, instead of tabs), but we can stick to this if you prefer it.

Also, we removed the "next/cancel" buttons, and numbers from tabs, to make it feel less like a "wizard", hope that's ok.

The sidebar can be collapsed by dragging on the right margin.

Let me know if you have any questions!

**Comment by awright** [comment]
Thanks Szymon. We'll begin to discuss internally. Can you start to make the
foundation functionality, even if you don't have 100% sign-off?

**Comment by szymonkaliski** [comment]
Sure, we'll start working on the overall layout of the elements, since that shouldn't change too much now I believe.

**Comment by awright** [comment]
Immediate goal is to get a functional layout. @szymon Will put a functioning version on test server. Will review timeline (hopefully in the coming week). @mataharimhairi looking to give team in Indonesia for feedback.  Will send to HOT slack team. 

Current functionality:
- Close done: 
   - The discussed layout of thigns
   - Switching of tabs
   - Search bar
   - Zoom in/out
   - Date selection working 
- Need more work
   - Play bar working in master branch. Play not working - then the dates will be working 
   - Full screen not working yet
   - Share needs thought and nicer design
   - Website buttons are not working. eg. "About" "Create" 

@smit1678 A functioning version does not need styling, but an application we can put in front of people for feedback
@mataharimhairi & Alyssa will put together targeted questions for gathering feedback

Team agrees 
- To move away from editing and date tools in play bar. 
- Do not need specific "hide" for the left hand sidebar. 
- Counting the number of features is not possible. Is an insane amount of processing. 
- Left hand slide bar (for view) has context, on slide 6. Full screen removes that info. 
- Summary added to tab - with what you are sharing. Combination of 3 tabs "Description" "Feature" and "Date" 
- Do not need "Contact Us" "HOT" and "Fork"

**Comment by szymonkaliski** [comment]
Not sure if we should open another issue for timeline? Anyways here's what we can do:

What already is working:

- tabs switching on sidebar
- searching map
- zoom in/out
- switching styles of roads/buildings
- working export to video file (just map view exported, like we have in Gunung Agung animation examples)

What we can get working on monday (12.03):

- date buttons working (connected to "play" and what's visible on map)
- bottom play bar working (connected with dates and bottom right corner date)
- better "style" options, and background map layer switching
- button to hide sidebar behind left part of the screen, and show it again
- the "describe" can be filled out, but since we don't have "url sharing" it's not going to do anything yet
- all of the above live on our test server
- proposed timeline for next week or so (based on what we have on monday, and what we feel is a good next step)

What we would be the next after that (not in any specific order - tbd):

- "proper" design (colors, button styles, etc... - waiting for feedback on issue #27)
- "share modal" - all the options we need, and nicer layout
- "shared" url view (sharing by link, with sidebar filled with data - slide 6)
- "fullscreen" button in "create" mode, and in "shared" url
- "preview" sidebar button(? - or some other solution to "preview" the "url share" view)
- adding slide 1 (intro screen)
- figuring out what "learn" and "create" buttons should do
- figuring out if / how we want to overlay dates on video and gif exports
- localisation of the app

**Comment by awright** [comment]
Hi Szymon, Can you make a new ticket with this info? That way we can
separate conversations. I think this all is sounding good. I do have one
question about the preview sidebar timeline. So let's put it in a separate
ticket. Thanks!

**Comment by szymonkaliski** [comment]
@awright made Project Timeline issue for tracking this: #29
